# Generated by Django 2.1 on 2020-06-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
