# Generated by Django 2.1 on 2020-06-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_user',
            old_name='email_address',
            new_name='email',
        ),
    ]
